/**
 * This class is generated by jOOQ
 */
package music.spider.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import music.spider.jooq.tables.MusicSong;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicSongRecord extends UpdatableRecordImpl<MusicSongRecord> implements Record8<Long, Long, String, Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = -1525071824;

    /**
     * Setter for <code>music_spider.music_song.id</code>. 自增主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>music_spider.music_song.id</code>. 自增主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>music_spider.music_song.ranking_id</code>. 排行榜ID
     */
    public void setRankingId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>music_spider.music_song.ranking_id</code>. 排行榜ID
     */
    public Long getRankingId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>music_spider.music_song.name</code>. 歌曲名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>music_spider.music_song.name</code>. 歌曲名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>music_spider.music_song.ranking_no</code>. 排名
     */
    public void setRankingNo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>music_spider.music_song.ranking_no</code>. 排名
     */
    public Integer getRankingNo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>music_spider.music_song.time</code>. 歌曲时长，单位：秒
     */
    public void setTime(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>music_spider.music_song.time</code>. 歌曲时长，单位：秒
     */
    public Integer getTime() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>music_spider.music_song.singer</code>. 歌手
     */
    public void setSinger(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>music_spider.music_song.singer</code>. 歌手
     */
    public String getSinger() {
        return (String) get(5);
    }

    /**
     * Setter for <code>music_spider.music_song.url</code>. 网易云音乐链接
     */
    public void setUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>music_spider.music_song.url</code>. 网易云音乐链接
     */
    public String getUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>music_spider.music_song.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>music_spider.music_song.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MusicSong.MUSIC_SONG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MusicSong.MUSIC_SONG.RANKING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MusicSong.MUSIC_SONG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MusicSong.MUSIC_SONG.RANKING_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MusicSong.MUSIC_SONG.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MusicSong.MUSIC_SONG.SINGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MusicSong.MUSIC_SONG.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MusicSong.MUSIC_SONG.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRankingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRankingNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSinger();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value2(Long value) {
        setRankingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value4(Integer value) {
        setRankingNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value5(Integer value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value6(String value) {
        setSinger(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value7(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicSongRecord values(Long value1, Long value2, String value3, Integer value4, Integer value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MusicSongRecord
     */
    public MusicSongRecord() {
        super(MusicSong.MUSIC_SONG);
    }

    /**
     * Create a detached, initialised MusicSongRecord
     */
    public MusicSongRecord(Long id, Long rankingId, String name, Integer rankingNo, Integer time, String singer, String url, Timestamp updateTime) {
        super(MusicSong.MUSIC_SONG);

        set(0, id);
        set(1, rankingId);
        set(2, name);
        set(3, rankingNo);
        set(4, time);
        set(5, singer);
        set(6, url);
        set(7, updateTime);
    }
}
