/**
 * This class is generated by jOOQ
 */
package music.spider.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import music.spider.jooq.tables.MusicComment;
import music.spider.jooq.tables.MusicRanking;
import music.spider.jooq.tables.MusicSong;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicSpider extends SchemaImpl {

    private static final long serialVersionUID = 1593302598;

    /**
     * The reference instance of <code>music_spider</code>
     */
    public static final MusicSpider MUSIC_SPIDER = new MusicSpider();

    /**
     * The table <code>music_spider.music_comment</code>.
     */
    public final MusicComment MUSIC_COMMENT = music.spider.jooq.tables.MusicComment.MUSIC_COMMENT;

    /**
     * The table <code>music_spider.music_ranking</code>.
     */
    public final MusicRanking MUSIC_RANKING = music.spider.jooq.tables.MusicRanking.MUSIC_RANKING;

    /**
     * The table <code>music_spider.music_song</code>.
     */
    public final MusicSong MUSIC_SONG = music.spider.jooq.tables.MusicSong.MUSIC_SONG;

    /**
     * No further instances allowed
     */
    private MusicSpider() {
        super("music_spider", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MusicComment.MUSIC_COMMENT,
            MusicRanking.MUSIC_RANKING,
            MusicSong.MUSIC_SONG);
    }
}
