/**
 * This class is generated by jOOQ
 */
package music.spider.jooq;


import javax.annotation.Generated;

import music.spider.jooq.tables.MusicComment;
import music.spider.jooq.tables.MusicRanking;
import music.spider.jooq.tables.MusicSong;


/**
 * Convenience access to all tables in music_spider
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>music_spider.music_comment</code>.
     */
    public static final MusicComment MUSIC_COMMENT = music.spider.jooq.tables.MusicComment.MUSIC_COMMENT;

    /**
     * The table <code>music_spider.music_ranking</code>.
     */
    public static final MusicRanking MUSIC_RANKING = music.spider.jooq.tables.MusicRanking.MUSIC_RANKING;

    /**
     * The table <code>music_spider.music_song</code>.
     */
    public static final MusicSong MUSIC_SONG = music.spider.jooq.tables.MusicSong.MUSIC_SONG;
}
