/**
 * This class is generated by jOOQ
 */
package music.spider.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import music.spider.jooq.Keys;
import music.spider.jooq.MusicSpider;
import music.spider.jooq.tables.records.MusicRankingRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicRanking extends TableImpl<MusicRankingRecord> {

    private static final long serialVersionUID = 1635787409;

    /**
     * The reference instance of <code>music_spider.music_ranking</code>
     */
    public static final MusicRanking MUSIC_RANKING = new MusicRanking();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MusicRankingRecord> getRecordType() {
        return MusicRankingRecord.class;
    }

    /**
     * The column <code>music_spider.music_ranking.id</code>.
     */
    public final TableField<MusicRankingRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>music_spider.music_ranking.name</code>.
     */
    public final TableField<MusicRankingRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>music_spider.music_ranking.url</code>.
     */
    public final TableField<MusicRankingRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>music_spider.music_ranking.update_time</code>. 更新时间
     */
    public final TableField<MusicRankingRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * Create a <code>music_spider.music_ranking</code> table reference
     */
    public MusicRanking() {
        this("music_ranking", null);
    }

    /**
     * Create an aliased <code>music_spider.music_ranking</code> table reference
     */
    public MusicRanking(String alias) {
        this(alias, MUSIC_RANKING);
    }

    private MusicRanking(String alias, Table<MusicRankingRecord> aliased) {
        this(alias, aliased, null);
    }

    private MusicRanking(String alias, Table<MusicRankingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MusicSpider.MUSIC_SPIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MusicRankingRecord, Long> getIdentity() {
        return Keys.IDENTITY_MUSIC_RANKING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MusicRankingRecord> getPrimaryKey() {
        return Keys.KEY_MUSIC_RANKING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MusicRankingRecord>> getKeys() {
        return Arrays.<UniqueKey<MusicRankingRecord>>asList(Keys.KEY_MUSIC_RANKING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRanking as(String alias) {
        return new MusicRanking(alias, this);
    }

    /**
     * Rename this table
     */
    public MusicRanking rename(String name) {
        return new MusicRanking(name, null);
    }
}
