/**
 * This class is generated by jOOQ
 */
package music.spider.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicSong implements Serializable {

    private static final long serialVersionUID = 714114815;

    private Long      id;
    private Long      rankingId;
    private String    name;
    private Integer   rankingNo;
    private Integer   time;
    private String    singer;
    private String    url;
    private Timestamp updateTime;

    public MusicSong() {}

    public MusicSong(MusicSong value) {
        this.id = value.id;
        this.rankingId = value.rankingId;
        this.name = value.name;
        this.rankingNo = value.rankingNo;
        this.time = value.time;
        this.singer = value.singer;
        this.url = value.url;
        this.updateTime = value.updateTime;
    }

    public MusicSong(
        Long      id,
        Long      rankingId,
        String    name,
        Integer   rankingNo,
        Integer   time,
        String    singer,
        String    url,
        Timestamp updateTime
    ) {
        this.id = id;
        this.rankingId = rankingId;
        this.name = name;
        this.rankingNo = rankingNo;
        this.time = time;
        this.singer = singer;
        this.url = url;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRankingId() {
        return this.rankingId;
    }

    public void setRankingId(Long rankingId) {
        this.rankingId = rankingId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRankingNo() {
        return this.rankingNo;
    }

    public void setRankingNo(Integer rankingNo) {
        this.rankingNo = rankingNo;
    }

    public Integer getTime() {
        return this.time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    public String getSinger() {
        return this.singer;
    }

    public void setSinger(String singer) {
        this.singer = singer;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MusicSong (");

        sb.append(id);
        sb.append(", ").append(rankingId);
        sb.append(", ").append(name);
        sb.append(", ").append(rankingNo);
        sb.append(", ").append(time);
        sb.append(", ").append(singer);
        sb.append(", ").append(url);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
