/**
 * This class is generated by jOOQ
 */
package music.spider.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicRanking implements Serializable {

    private static final long serialVersionUID = 1327298260;

    private Long      id;
    private String    name;
    private String    url;
    private Timestamp updateTime;

    public MusicRanking() {}

    public MusicRanking(MusicRanking value) {
        this.id = value.id;
        this.name = value.name;
        this.url = value.url;
        this.updateTime = value.updateTime;
    }

    public MusicRanking(
        Long      id,
        String    name,
        String    url,
        Timestamp updateTime
    ) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MusicRanking (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
